version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
environment:
  password:
    secure: SHp3N2vcWjhD8xFFopC4ufWnsSbyDowKSa+gCLRrIFA=
install:
- cmd: set PATH=C:\Ruby25-x64\bin;C:\Python27-x64;%PATH%
- cmd: gem install bundler
build_script:
- cmd: >-
    build.cmd CI
artifacts:
- path: _site
  name: Site