name: build

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . -t blog
      - name: Copy generated files locally
        run: |
          id=$(docker create blog)
          docker cp $id:/usr/share/nginx/html ./site
          docker rm -v $id
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./site